local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<leader>e", builtin.live_grep, {})
vim.keymap.set("v", "<leader>e", builtin.grep_string, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>gk", builtin.git_commits, {})
vim.keymap.set("n", "<leader>gj", builtin.git_bcommits, {})
vim.keymap.set("n", "<leader>gbr", builtin.git_branches, {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>ps", function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)

require("telescope").load_extension("fzf")
