vim.api.nvim_set_keymap("n", "<space>ga", ":Git add %:p<CR><CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gs", ":vertical Git<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gc", ":Git commit -v -q<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gn", ":Git commit -v --amend --no-edit<CR><CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gd", ":Gdiff<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gh", ":Gclog %<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>ge", ":Gedit<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gr", ":Gread<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gw", ":Gwrite<CR><CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gl", ":silent! Glog<CR>:bot copen<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gp", ":Ggrep<Space>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gm", ":Gmove<Space>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gb", ":Git branch<Space>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>go", ":Git checkout<Space>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gps", ":Git push<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<space>gpl", ":Git pull<CR>", { noremap = true })
vim.api.nvim_set_keymap("c", "blame", "Git blame", { silent = true, noremap = true })
